/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instituto.vistas;

/**
 *
 * @author azu15
 */
public class MenuPrincipal extends javax.swing.JFrame {
           
           
    public MenuPrincipal() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setSize(800, 600);
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jbRegistrarme = new javax.swing.JButton();
        jbAlumnosPorCurso = new javax.swing.JButton();
        jbSistemaDeAlumnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbCursos = new javax.swing.JButton();
        jbIdAlumnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(19, 103, 128));
        escritorio.setMaximumSize(new java.awt.Dimension(800, 600));
        escritorio.setMinimumSize(new java.awt.Dimension(800, 600));
        escritorio.setPreferredSize(new java.awt.Dimension(800, 600));

        jbRegistrarme.setBackground(new java.awt.Color(48, 165, 176));
        jbRegistrarme.setText("Registrarme ");
        jbRegistrarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarmeActionPerformed(evt);
            }
        });

        jbAlumnosPorCurso.setBackground(new java.awt.Color(48, 165, 176));
        jbAlumnosPorCurso.setText("Alumnos por Curso");
        jbAlumnosPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlumnosPorCursoActionPerformed(evt);
            }
        });

        jbSistemaDeAlumnos.setBackground(new java.awt.Color(48, 165, 176));
        jbSistemaDeAlumnos.setText("Sistema de Alumnos");
        jbSistemaDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSistemaDeAlumnosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel1.setText("INSTITUTO ABIERTO DE FORMACION PROFESIONAL ARGENTINA ");

        jbCursos.setText("Cursos");
        jbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCursosActionPerformed(evt);
            }
        });

        jbIdAlumnos.setText("¿Cual es mi ID de Alumno?");
        jbIdAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIdAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSistemaDeAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbRegistrarme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlumnosPorCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addComponent(jbIdAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbRegistrarme, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jbIdAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jbSistemaDeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addComponent(jbAlumnosPorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarmeActionPerformed
       Registrarme registrarme = new Registrarme();
       registrarme.setVisible(true);
       this.dispose();
       //haace visible la ventana que estamos instanciando
       
       // cierra la ventana actual (menu principal)
       
    }//GEN-LAST:event_jbRegistrarmeActionPerformed

    private void jbAlumnosPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlumnosPorCursoActionPerformed
        AlumnosPorCurso alumnosPorCurso = new AlumnosPorCurso();
        alumnosPorCurso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAlumnosPorCursoActionPerformed

    private void jbSistemaDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSistemaDeAlumnosActionPerformed
        SistemaDeAlumnos sistemaDeAlumnos = new SistemaDeAlumnos();
        sistemaDeAlumnos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSistemaDeAlumnosActionPerformed

    private void jbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCursosActionPerformed
        Cursos cursos = new Cursos();
        cursos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCursosActionPerformed

    private void jbIdAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIdAlumnosActionPerformed
        ListaDeAlumnosConId lista = new ListaDeAlumnosConId();
        lista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbIdAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAlumnosPorCurso;
    private javax.swing.JButton jbCursos;
    private javax.swing.JButton jbIdAlumnos;
    private javax.swing.JButton jbRegistrarme;
    private javax.swing.JButton jbSistemaDeAlumnos;
    // End of variables declaration//GEN-END:variables
}
